# Generated by Django 5.0.3 on 2024-03-17 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kirrurl',
            name='slug',
        ),
    ]
