# Generated by Django 5.0.3 on 2024-03-18 20:01

import shortener.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_remove_kirrurl_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kirrurl',
            name='url',
            field=models.CharField(max_length=200, validators=[shortener.validators.validate_url, shortener.validators.validate_dot_com]),
        ),
    ]
